version: '3'
services:
  liferay:
    image: liferay/portal:7.2.1-ga2
    environment:
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME: com.mysql.cj.jdbc.Driver
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL: jdbc:mysql://database:3306/${mysql_database_name}?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME: ${mysql_user_name}
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD: ${mysql_user_password}
    ports:
      - 8080:8080
    networks:
      - liferay-net
    volumes:
      - ./06_liferay:/mnt/liferay
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: testroot
      MYSQL_DATABASE: ${mysql_database_name}
      MYSQL_USER: ${mysql_user_name}
      MYSQL_PASSWORD: ${mysql_user_password}
    networks:
      liferay-net:
        aliases:
          - database
    volumes:
      - volume-mysql:/var/lib/mysql
  search:
    image: elasticsearch:6.5.4
    networks:
      liferay-net:
        aliases:
          - elasticsearch
networks:
  liferay-net:
    driver: bridge
volumes:
  volume-mysql: