version: '3.7'
services:
  reverse-proxy:
    image: traefik:v2.1.4
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.swarmmode=true"
      - "--accesslog"
      - "--log.level=DEBUG"
    ports: # we want traefik to be the only element accessible from outside
      - "80:80"
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - liferay-net_04
    deploy:
      placement:
        constraints:
          - node.role == manager
  liferay:
    image: liferay/portal:7.2.1-ga2
    environment:
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_LASS_UPPERCASEN_AME: com.mysql.cj.jdbc.Driver
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL: jdbc:mysql://database:3306/${mysql_database_name}?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME: ${mysql_user_name}
      LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD: ${mysql_user_password}
      LIFERAY_BROWSER_PERIOD_LAUNCHER_PERIOD_URL:
      JGROUPS_CONFIG_FILE_PATH: /tomcat/webapps/ROOT/WEB-INF/classes${jgroups_config_file}
      LIFERAY_CLUSTER_PERIOD_LINK_PERIOD_ENABLED: "true"
      LIFERAY_CLUSTER_PERIOD_LINK_PERIOD_AUTODETECT_PERIOD_ADDRESS: database:3306
      LIFERAY_CLUSTER_PERIOD_LINK_PERIOD_CHANNEL_PERIOD_PROPERTIES_PERIOD_CONTROL: ${jgroups_config_file}
      LIFERAY_CLUSTER_PERIOD_LINK_PERIOD_CHANNEL_PERIOD_PROPERTIES_PERIOD_TRANSPORT_PERIOD__NUMBER0_: ${jgroups_config_file}
      LIFERAY_WEB_PERIOD_SERVER_PERIOD_DISPLAY_PERIOD_NODE: "true"
    volumes:
      - ./liferay:/mnt/liferay
      - volume_04-doclib:/opt/liferay/data/document_library
    networks:
      - liferay-net_04
    deploy:
      labels: # in swarm, traefik labels must be defined at the service level, not at container one. See https://docs.traefik.io/routing/providers/docker/
        - traefik.enable=true
        - traefik.http.services.liferay-service.loadbalancer.server.port=8080
        - traefik.http.routers.liferay-router.rule=Host(`${app_host_name}`)
      replicas: 1
  database:
    image: mysql:8.0
    command:
      - "--init-file=/docker-entrypoint-initdb.d/clean_jgroups.sql"
    environment:
      MYSQL_ROOT_PASSWORD: testroot
      MYSQL_DATABASE: ${mysql_database_name}
      MYSQL_USER: ${mysql_user_name}
      MYSQL_PASSWORD: ${mysql_user_password}
    networks:
      liferay-net_04:
        aliases:
          - database
    volumes:
      - volume_04-mysql_8.0:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
  search:
    image: elasticsearch:7.3.0
    networks:
      liferay-net_04:
        aliases:
          - search
    volumes:
      - volume_04-elasticsearch_7.3.0:/usr/share/elasticsearch/data
      - ../01_liferay+mysql+elasticsearch-7.3/elasticsearch/plugins-7.3.0:/usr/share/elasticsearch/plugins
    environment:
      cluster.name: LiferayElasticsearchCluster
      node.name: LiferayElasticsearchCluster_node1
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
networks:
  liferay-net_04:
    driver: overlay
volumes:
  volume_04-mysql_8.0:
  volume_04-doclib:
  volume_04-elasticsearch_7.3.0: